### PR TITLE
Build jfx into jdk / jre for win

### PR DESCRIPTION
**Pull request by rgithubli**
Build jfx into jdk / jre.

Test: with internal infra, can run an jfx app with packaged msi.

### CODE REVIEW

**Review by lutkerd — COMMENTED** [review]
I think we need to ensure all VCRuntime files are copied. I think this somehow doesn't pull in concrt140.dll which we need.

**Comment by rgithubli** [comment]
Pushed wrong commits. Removed my remote branch to redo, which unintentionally closed this pr. Opening another one.

**Comment by rgithubli** [comment]
Try reopen in this pr in place...

**Comment by rgithubli** [comment]
OK github still keeps this pr closed. Use this one: https://github.com/corretto/corretto-8/pull/499

**Pull request closed without merging**
