### PR TITLE
Fix merges from jdk8u

### PR DESCRIPTION
**Pull request by yftsai**
Thank you for taking the time to help improve OpenJDK and Corretto.

If your pull request concerns a security vulnerability then please do not file it.
Instead, report the problem by email to aws-security@amazon.com.
(You can find more information regarding security issues at https://aws.amazon.com/security/vulnerability-reporting/.)

Otherwise, if your pull request concerns OpenJDK 8
and is not specific to Corretto 8,
then we ask you to redirect your contribution to the OpenJDK project.
See http://openjdk.java.net/contribute/ for details on how to do that.

If your issue is specific to Corretto 8,
then you are in the right place.
Please fill in the following information about your pull request.

### Description

The conflict came from Corretto patches in jdk/test/javax/net/ssl/TLS/TLSClientPropertyTest.java

### Platform information
    Works on OS: [e.g. Amazon Linux 2 only]
    Applies to version [e.g. "build 1.8.0_192-amazon-corretto-preview-b12" (output from "java -version")]

### Contribution confirmation

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by caojoshua** [comment]
I think this is OK. Only one conflict, which is in a test file. If the test is passing, I am not too concerned.

Do you know why we have a conflict here? Are we missing a patch, or do we have anything extra in Corretto-8?

**Comment by yftsai** [comment]
> Do you know why we have a conflict here? Are we missing a patch, or do we have anything extra in Corretto-8?

The conflict is caused by 7b6d16 which is a corretto patch to keep using TLS1.2.

**Comment by caojoshua** [comment]
> > Do you know why we have a conflict here? Are we missing a patch, or do we have anything extra in Corretto-8?
> 
> The conflict is caused by 7b6d16 which is a corretto patch to keep using TLS1.2.

I don't see 7b6d16 [here](https://github.com/corretto/corretto-8/search?q=7b6d16).

**Comment by yftsai** [comment]
This [one](https://github.com/search?l=&q=7b6d16bf467d537847df9c012a7d1596f46de784&type=commits).

**Review by caojoshua — APPROVED** [review]

**Pull request merged**
