### PR TITLE
OpenJFX WebKit enabled plus patches

### PR DESCRIPTION
**Pull request by jschwartzenberg**
### Description
This PR enables WebKit in OpenJFX, so that `libjfxwebkit.so` is built and adds some patches to solve issues specific to WebKit. WebKit adds some dependencies to the build, notably GCC > 6, Python 2.7 and Ruby (1.9 or higher). Patches were taken from:
https://github.com/ojdkbuild/upstream_openjfx-8u
As this repository contains non-relevant patches as well and lacks history, I base ordering on my own version:
https://github.com/jschwartzenberg/openjfx8

### Related issues
JDK-8219539
JDK-8220147
JDK-8215799

### Motivation and context
These fixes were backported into the ojdkbuild project. Enabling WebKit allows projects relying on WebKit support in JavaFX to move to Corretto.

### How has this been tested?
Compilation plus running a sample on RHEL6. It would be good to test this on more platforms.

### Platform information
    Works on OS: all
    Applies to version: latest

### Additional context
OpenJFX 8 is not maintained anymore by Oracle. The original Mercurial repository stopped receiving commits in January 2019. Because Corretto does not have WebKit enabled, I created an initial PR without the WebKit patches, #149. This is the follow-up PR mentioned which enables WebKit with the patches that concern it.

### Contribution confirmation

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ziyiluo** [comment]
@jschwartzenber Thank you for your PR and sorry for the late response. There's an issue (#26) for enabling the webkit and media features in Corretto 8. Please refer to this reply: https://github.com/corretto/corretto-8/issues/26#issuecomment-472099025. In short, this enhancement has licensing issue and is non-trivial. We are still gathering data to support our decision-making.

**Comment by jschwartzenberg** [comment]
> In short, this enhancement has licensing issue and is non-trivial. We are still gathering data to support our decision-making.

Hi @ziyiluo I only enabled WebKit, not the media parts. Only the media parts have license issues. WebKit is LGPL. I'll make a note in the ticket.

**Comment by chrisvire** [comment]
@ziyiluo Can this be reopened since this if for WebKit that is LGPL and not the media parts?  We need just the WebKit parts of JavaFX for our cross-platform app.

**Comment by jschwartzenberg** [comment]
@chrisvire is this is reopened, I'll have to update it though. I found some issues. The media part is partially required for most webpages, I think to render images. The AVPlugin part that needs libraries that are not always available can be easily disabled independently from that however.

Can I ask which platforms are you are trying to support with your application?

**Comment by yishaigalatzer** [comment]
We going to look again at the licensing issue. I am concerned with taking a new dependency on Python 2.7, Python 2.7 is quickly reaching end of life (https://pythonclock.org/)

**Pull request closed without merging**
